In [1]:
import pickle

In [9]:
import numpy as np

# Function to create a new dataset based on quantized deltas
def recreate_dataset(original_data, quantized_data):
    recreated_data = {}  # Dictionary to store the recreated dataset

    for video_key, video_data in original_data.items():
        print(f"Processing video: {video_key}")

        # Extract the original keypoints and quantized deltas
        original_keypoints = video_data['keypoints']  # Shape: (frames, points, 3)
        quantized_keypoints = quantized_data[video_key]['keypoints']  # Shape: (frames, points, 3)

        # Step 1: Initialize the recreated dataset with the first frame's keypoints
        frames, points, features = original_keypoints.shape
        recreated_frames = np.zeros((frames, points, features), dtype=np.float32)

        # Use the first frame's keypoints as the starting frame
        recreated_frames[0] = original_keypoints[0]

        # Step 2: Iteratively add quantized deltas to recreate the dataset
        for i in range(1, frames):
            recreated_frames[i, :, 0] = recreated_frames[i - 1, :, 0] + quantized_keypoints[i, :, 0]  # X
            recreated_frames[i, :, 1] = recreated_frames[i - 1, :, 1] + quantized_keypoints[i, :, 1]  # Y
            recreated_frames[i, :, 2] = quantized_keypoints[i, :, 2]  # Confidence (direct from quantized)

        # Step 3: Store the recreated data in the same format
        recreated_data[video_key] = {'keypoints': recreated_frames}
        # break  # Process only one video for now

    return recreated_data


In [10]:
# Load the datasets
def load_pkl(file_path):
    with open(file_path, 'rb') as f:
        return pickle.load(f)

original_data_path = '/nas/Dataset/Phoenix/phoenix-2014-keypoints.pkl'
quantized_data_path = '/nas/Chingiz/sing_language/vector/phoenix_quantized_all_conf_same.pkl'

original_data = load_pkl(original_data_path)
quantized_data = load_pkl(quantized_data_path)

# Recreate the dataset for one video
recreated_data = recreate_dataset(original_data, quantized_data)

# Save the recreated dataset for testing
with open('/nas/Chingiz/sing_language/vector/recreated_video.pkl', 'wb') as f:
    pickle.dump(recreated_data, f)

print("Recreated dataset saved for one video.")


Processing video: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-0/1/01April_2010_Thursday_heute
Processing video: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-2/1/01April_2010_Thursday_heute
Processing video: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-3/1/01April_2010_Thursday_heute
Processing video: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-4/1/01April_2010_Thursday_heute
Processing video: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-6/1/01April_2010_Thursday_heute
Processing video: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-7/1/01April_2010_Thursday_heute
Processing video: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-8/1/01April_2010_Thursday_heute
Processing video: fullFrame-210x260px/train/01April_2010_Thursday_tagesschau_default-0/1/01April_2010_Thursday_tagesschau
Processing video: fullFrame-210x260px/train/01April_2010_Thursday_tagesschau_default-2/1/01Apr

In [11]:
# Load and inspect the recreated dataset
# recreated_video = load_pkl('/nas/Chingiz/sing_language/vector/recreated_video_one.pkl')
recreated_video = load_pkl('/nas/Dataset/Phoenix/phoenix-2014-keypoints.pkl')

# Print the shape and sample points from the recreated dataset
video_key = list(recreated_video.keys())[0]
print(f"Video Key: {video_key}")
print("Recreated keypoints shape:", recreated_video[video_key]['keypoints'].shape)
print("First frame:\n", recreated_video[video_key]['keypoints'][0])
print("Second frame:\n", recreated_video[video_key]['keypoints'][1])
print("Third frame:\n", recreated_video[video_key]['keypoints'][2])

Video Key: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-0/1/01April_2010_Thursday_heute
Recreated keypoints shape: (176, 133, 3)
First frame:
 [[1.0938e+02 4.8531e+01 9.7266e-01]
 [1.1800e+02 4.1219e+01 9.7949e-01]
 [9.9062e+01 4.3000e+01 9.8486e-01]
 [1.2988e+02 4.9188e+01 8.9648e-01]
 [8.8062e+01 5.3625e+01 8.8525e-01]
 [1.5500e+02 1.1512e+02 8.7744e-01]
 [6.6938e+01 1.1838e+02 8.6328e-01]
 [1.7938e+02 1.9888e+02 8.0566e-01]
 [4.2719e+01 2.0688e+02 8.1543e-01]
 [1.5900e+02 2.1812e+02 9.3945e-01]
 [8.0250e+01 2.2550e+02 9.1895e-01]
 [1.4550e+02 2.4550e+02 7.8027e-01]
 [8.3688e+01 2.4662e+02 8.0273e-01]
 [1.0556e+02 7.0812e+01 1.2134e-01]
 [9.2500e+01 5.6625e+01 1.0779e-01]
 [1.2925e+02 2.3325e+02 2.5146e-01]
 [8.8000e+01 4.1469e+01 3.0273e-01]
 [1.2850e+02 2.3162e+02 4.6387e-01]
 [1.2875e+02 2.3188e+02 4.7510e-01]
 [1.1844e+02 2.5212e+02 3.4741e-01]
 [1.0106e+02 2.3875e+02 4.2236e-01]
 [1.0119e+02 2.3875e+02 4.2236e-01]
 [1.1862e+02 2.5300e+02 3.6646e-01]
 [8.8438e+01

In [15]:
# Load and inspect the recreated dataset
recreated_video = load_pkl('/nas/Chingiz/sing_language/vector/recreated_video.pkl')
# recreated_video = load_pkl('/nas/Dataset/Phoenix/phoenix-2014-keypoints.pkl')

# Print the shape and sample points from the recreated dataset
video_key = list(recreated_video.keys())[0]
print(f"Video Key: {video_key}")
print("Recreated keypoints shape:", recreated_video[video_key]['keypoints'].shape)
print("First frame:\n", recreated_video[video_key]['keypoints'][0])
print("Second frame:\n", recreated_video[video_key]['keypoints'][1])
print("Third frame:\n", recreated_video[video_key]['keypoints'][2])

Video Key: fullFrame-210x260px/train/01April_2010_Thursday_heute_default-0/1/01April_2010_Thursday_heute
Recreated keypoints shape: (176, 133, 3)
First frame:
 [[1.09375000e+02 4.85312500e+01 9.72656250e-01]
 [1.18000000e+02 4.12187500e+01 9.79492188e-01]
 [9.90625000e+01 4.30000000e+01 9.84863281e-01]
 [1.29875000e+02 4.91875000e+01 8.96484375e-01]
 [8.80625000e+01 5.36250000e+01 8.85253906e-01]
 [1.55000000e+02 1.15125000e+02 8.77441406e-01]
 [6.69375000e+01 1.18375000e+02 8.63281250e-01]
 [1.79375000e+02 1.98875000e+02 8.05664062e-01]
 [4.27187500e+01 2.06875000e+02 8.15429688e-01]
 [1.59000000e+02 2.18125000e+02 9.39453125e-01]
 [8.02500000e+01 2.25500000e+02 9.18945312e-01]
 [1.45500000e+02 2.45500000e+02 7.80273438e-01]
 [8.36875000e+01 2.46625000e+02 8.02734375e-01]
 [1.05562500e+02 7.08125000e+01 1.21337891e-01]
 [9.25000000e+01 5.66250000e+01 1.07788086e-01]
 [1.29250000e+02 2.33250000e+02 2.51464844e-01]
 [8.80000000e+01 4.14687500e+01 3.02734375e-01]
 [1.28500000e+02 2.31625